### ISSUE TITLE
아이템 18. 상속보다는 컴포지션을 사용하라

### ISSUE THREAD

**Issue by ksy90101** [Meet-Coder-Study/book-effective-java#18]

**Comment by KimDoubleB** [comment]
아이템 18번을 하며 Properties에 대해 궁금한 점이 있어 이렇게 이슈를 작성합니다 !

120p에 보시면 아래와 같은 설명이 있습니다.
> Properties의 인스턴스 p가 있을 때, p.getProperty(key)와 p.get(key)는 결과가 다를 수 있다. 전자가 Properties의 기본 동작인 데 반해, 후자는 Properties의 상위 클래스인 Hashtable로부터 물려받은 메서드이기 때문이다.

> Properties는 키와 값으로 문자열만 허용하도록 설계하려 했으나, 상위 클래스인 Hashtable의 메서드를 직접 호출하면 이 불변식을 깨버릴 수 있다. 불변식이 한번 깨지면 load, store 같은 다른 Properties API를 더 이상 사용할 수 없다.

말 그대로 Properties에 `put`으로 string이 아닌 데이터도 넣을 수 있고, 이를 사용하면 `load`, `store` 시에 제대로 작동하지 않는 다는 것을 볼 수 있었습니다. 또한 `getProperty`, `setProperty` 코드가 내부적으로 `get`과 `put`을 사용하고 있던 것도 확인할 수 있었습니다.

그럼, 궁금한 점이 왜 Properties는 `get`, `put`을 오버라이드해서 `getProperty`, `setProperty` 기능을 하도록 만들지 않고, 새로 `getProperty`, `setProperty`를 만든 것인가요?

다시 말해서, 키와 값을 문자열로만 제한하려했고, 문자열이 아닌 데이터에서는 다른 Properties API를 지원하지도 않는데, 왜 취약점일 수 있는 `get`, `put`을 그대로 둔 것일까요? 이런 의문이 드는 것이 책에서 말하는 ‘문제’라는 것인가요?

**Comment by pkch93** [comment]
책에서도 잘못된 상속의 예시로 `java.util.Properties`를 소개하고 있는걸로 보이는데요.
아마 현재 보배님께서 보고 계신 `java.util.Properties`는 개선이 이뤄진 이후의 `java.util.Properties`라서 `get`, `put`을 `getProperty`, `setProperty`처럼 구현해야하지 않나라고 생각이 드셨을거로 생각이 되는데요. `혹시 java 8 이상 버전인가요? java 8에서도 여전히 개선이 안된걸로 보여서요`

아마 java 8 `저는 openjdk zulu 1.8.0_232 입니다.`의 `java.util.Properties`를 보시면 map도 없고 `get`, `put` 등을 오버라이드한 코드도 없음을 확인하실 수 있으실꺼에요. 때문에 아마 기존의 `java.util.Properties`는 `HashTable`을 상속하고 있는 구조이기 때문에 `HashTable`이 가진 `get`, `put` 등을 `java.util.Properties`의 인스턴스에서도 그대로 사용했을 것으로 보이네요.

때문에 책에서 나와있는거처럼 `java.util.Properties`가 제공하고자 하는 기능인 `getProperty`와 `setProperty`와 `HashTable`의 `get`, `put`의 불일치가 있었을 것으로 보여요. 그로인한 버그들도 있었을거구요.

때문에 현재의 java에서는 `HashTable`이 가지고 있는 메서드를 `java.util.Properties`에서 그대로 노출하는 문제를 보완하고자 `ConcurrentHashMap`의 `map`을 가지고 조합형태로 막아놓은 걸로 보입니다.

보배님께서 드셨던 의문이 결국은 기존 `java.util.Properties`가 `HashTable`을 상속해서 발생한 문제의 해결책이기 때문에 그런 의문이 드신게 아닌가 생각이듭니다.

**Comment by KimDoubleB** [comment]
안녕하세요. 경철님! 의견 감사드립니다.

제가 너무 Java와 api는 안전할 것이란 생각이 내면에 자리 잡고 있어서 이런 질문이 나왔던 것 같습니다 😅  (완벽한 코드는 어디에도 없는데 말이죠) 책에서도 문제라고 언급을 하고 있지만, 무언가 저렇게 만든 이유가 있지 않을까 궁금해서 질문드렸던 것입니다 하하....

저는 java 11을 사용하고 있는데요, 경철님 말씀대로 java 8과는 차이가 있는 것을 볼 수 있었습니다 !
차이에 대해 좀 더 보며 공부를 해봐야겠습니다 ! 다시 한번 감사드립니다 😄

**Comment by rockjoon** [comment]
> 다시 말해서, 키와 값을 문자열로만 제한하려했고, 문자열이 아닌 데이터에서는 다른 Properties API를 지원하지도 않는데, 왜 취약점일 수 있는 get, put을 그대로 둔 것일까요? 이런 의문이 드는 것이 책에서 말하는 ‘문제’라는 것인가요?

HashTable에서 상속 받은 get, put을 그대로 둔 이유는 책에서 다음과 같이 설명하고 있네요 
```
이 문제가 밝혀졌을 때는 이미 수많은 사용자가 문자열 이외의 타입을 Properties의 키나 값으로 사용하고 있었다.
문제를 바로잡기에는 너무 늦어버린 것이다.
```
잘못 설계된 API이지만 이미 많은 사용자들이 사용하고 있어서 이를 수정하기에는 위험부담이 크다고 판단한 것 같습니다
