### ISSUE TITLE
아이템2. 생성자에 매개변수가 많다면 빌더를 고려하라

### ISSUE THREAD

**Issue by ksy90101** [Meet-Coder-Study/book-effective-java#2]

**Comment by ksy90101** [comment]
이 아이템과는 다른 내용이긴한데, 이 아이템에서 빌더 패턴을 이야기 하고 있어서 의문점이 생겼습니다.
Java API에서 StringBuilder와 StringBuffer가 빌더 패턴으로 구현되어 있다고 할 수 있을까요?

**Comment by shinsunyoung** [comment]
여기에서 소개하는 빌더 패턴을 말씀하신건지는 모르겠지만 만약 맞다면 관련이 없는 것 같아요 ... !

https://stackoverflow.com/questions/5238007/stringbuilder-and-builder-pattern

**Comment by rockjoon** [comment]
@ksy90101 
append 메서드가 메서드 체이닝 방식이라는 점에서 빌더 패턴과 비슷하긴 하지만

인스턴스를 단순히 public 생성자로 얻기 때문에 빌더 패턴과는 조금 다른 것 같습니다 !

**Comment by ksy90101** [comment]
이 아이템에서 자바빈즈패턴에서 얼리고(freezing)이 나오게 되는데, 아래와 같은 코드가 될거 같아요! 쓰지는 않고 불편함이 많지만 한번 참고해보세요~ (JavaScript에도 freezing이 있는거 같아요 ㅎㅎ )

https://softwareengineering.stackexchange.com/questions/369571/how-do-we-freeze-an-object-while-constructing-an-object-using-javabeans-pattern
