### ISSUE TITLE
아이템 37. ordinal 인덱싱 대신 EnumMap을 사용하라

### ISSUE THREAD

**Issue by ksy90101** [Meet-Coder-Study/book-effective-java#37]

**Comment by jiaekim123** [comment]
아이템 37 중간부터 스트림을 사용한 코드들이 자주 등장하는데요.
`Collectors.groupingBy`라던가 `Collectors.toMap`메서드를 사용할 때 Collectors를 생략하여 사용하기 위해 책에서는 미리 static으로 import 해두고 사용하는 것 같은데 다들 Collectors를 사용할 때 일반적으로 이렇게 사용하시나요? 자주 사용되는 메서드의 코드를 짧게 사용할 수 있는 점 외에 또 다른 이점이 있을까요?
`import static java.util.stream.Collectors.*;`

**Comment by pkch93** [comment]
보통 static import를 사용하는데요. 사실 메서드의 코드를 짧게 사용할 수 있다 이외에는 사실 다른 이점은 없는걸로 알고있는데요.
일반적인 경우에는 static import가 좀 더 가독성을 높여준다고 생각해요. 단, 몇몇 예외적인 경우에는 오히려 헷갈릴 수 있도록 만들때도 있는데요. 이런 상황들에 맞춰서 적절히 사용하면 되지 않을까 싶어요.

**Comment by ksy90101** [comment]
저도 경철님과 동일한 생각입니다.
몇몇 글에서는 가독성을 높이니 static import를 사용하는걸 권장하지만, 또 다른 글에서는 가독성을 낮춘다는 이야기도 있습니다.
개인적으로 선택이지 않을까 생각합니다 :) 
대신 한가지로 통일해야겠죠!?
저는 staitc import보다는 그냥 import로 사용하는 편입니다.. ㅎㅎ
이유는... 이미 습관이 import로 되버려서 와 static import로 만들기 귀찮아서... 일꺼 같네요 ㅎㅎ
