### ISSUE TITLE
아이템7. 다 쓴 객체 참조를 해제하라

### ISSUE THREAD

**Issue by ksy90101** [Meet-Coder-Study/book-effective-java#7]

**Comment by pkch93** [comment]
`item 7`에 메모리 누수 `Memory Leak`에 대한 내용이 일부 나오는데 같이 보면 좋을거 같은 링크들이 있어 공유합니다.

- [하나의 메모리 누수를 잡기까지](https://d2.naver.com/helloworld/1326256)
- [도움이 될수도 있는 JVM memory leak 이야기](https://woowabros.github.io/tools/2019/05/24/jvm_memory_leak.html)
- [자바 메모리누수(with 힙덤프) 분석하기](http://honeymon.io/tech/2019/05/30/java-memory-leak-analysis.html)
- [Java Reference와 GC](https://d2.naver.com/helloworld/329631)
- [How can I create a memory leak in Java?](https://stackoverflow.com/questions/6470651/how-can-i-create-a-memory-leak-in-java)
